// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,HASH:66, d0:68, d1:70, d2:72, d3:74, d4:76, d5:78, db:80, r0:84, r1:86, r2:88, r3:90, r4:92, r5:94, r6:96, r7:98, r8:100, r9:102, r10:104, r11:106, r12:108, r13:110, r14:112, r15:114, r16:116, r17:118, sp:120, ra:122}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&YOYQPOOOOQO'#Cr'#CrOYQPO'#CxOeQPO'#C`O#qQPO'#CdO%yQPO'#C_O&TQPO'#CpOOQO'#Cz'#CzO&YQPO'#CxQOQPOOOOQO'#Ce'#CeOOQO-E6p-E6pO&bQPO,59dO&jQPO,59OOOQO'#Ca'#CaO&oQPO'#ChO)OQPO'#DVO+[QPO'#CmOOQO'#C|'#C|OOQO'#Cs'#CsO+aQPO,58yOOQO'#Ci'#CiOOQO'#Co'#CoOOQO,59[,59[O+kQPO,59dO&bQPO,59dO+yQPO1G/OO,XQPO1G/OO,aQPO1G.jO,fQQO'#CjOOQO,59S,59SO,kQPO,59XOOQO-E6q-E6qOOQO,59`,59`OOQO-E6r-E6rO,pQPO7+$jOOQO7+$U7+$UOOQO,59U,59UOOQO1G.s1G.sPYQPO'#Cr",
  stateData: "-O~OkOSPOS~OmPOoROqYO~OUSXVSX_eXiSXmSXoSXqSXrSXsSXtSXuSXvSXwSXxSXzSX{SX|SX}SX!OSX!PSX!QSX!RSX!SSX!TSX!USX!VSX!WSX!XSX!YSX!ZSX![SX!]SX!^SX!_SX~OY]O~OUbOVbOo^OqYOreOseOteOueOveOweOxeOzfO{fO|fO}fO!OfO!PfO!QfO!RfO!SfO!TfO!UfO!VfO!WfO!XfO!YfO!ZfO![fO!]fO!^fO!_fO~OiRXmRX~P#vO_gO~OmPOilX~OmPOila~OVlO~O_mOU[XV[XbyXi[Xm[Xo[Xq[Xr[Xs[Xt[Xu[Xv[Xw[Xx[Xz[X{[X|[X}[X!O[X!P[X!Q[X!R[X!S[X!T[X!U[X!V[X!W[X!X[X!Y[X!Z[X![[X!][X!^[X!_[X~OUpXVpXbyXipXmpXopXqpXrpXspXtpXupXvpXwpXxpXzpX{pX|pX}pX!OpX!PpX!QpX!RpX!SpX!TpX!UpX!VpX!WpX!XpX!YpX!ZpX![pX!]pX!^pX!_pX~OboO~OiRamRa~P#vOmPOoROqYOila~OmPOoROqYOili~OmPOili~OZtO~O`uO~Oo^O~OmPOoROqYOilq~O",
  goto: "$hzPPP{!T!]PP!d!pPP!l!z#OPP!lP!l{#R#Z#o#uPPP$PP$SP$`PPPPPPPP$d]VOQhjsw]TOQhjswS`TdRvo[VOQhjswTbTdaSOQTdhjswT_TdRn_]UOQhjswQQOYZQhjswQhWSj[iRskQdTRpdQiWQk[TrikRXOQWOQ[QXqhjswTcTdTaTd",
  nodeNames: "⚠ Comment program Instruction InstructionName VariableName Number String FunctionCall FunctionName ParenLeft ParenRight Device DeviceName Channel Colon Integer DeviceProperty Dot Register Label LabelName",
  maxTerm: 61,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%s~R^XY}YZ!]]^}pq}rs!bst$Oxy$gyz$l!O!P$q!Q![$v![!]%]!c!}%b#R#S%b#T#o%b~!SRk~XY}]^}pq}~!bOm~~!eVOr!brs!zs#O!b#O#P#P#P;'S!b;'S;=`#x<%lO!b~#POV~~#SRO;'S!b;'S;=`#];=`O!b~#`WOr!brs!zs#O!b#O#P#P#P;'S!b;'S;=`#x;=`<%l!b<%lO!b~#{P;=`<%l!b~$TSP~OY$OZ;'S$O;'S;=`$a<%lO$O~$dP;=`<%l$O~$lOY~~$qOZ~~$vOb~R$}Q`QUP!O!P%T!Q![$vP%YPUP!Q![%T~%bO_~~%gSo~!Q![%b!c!}%b#R#S%b#T#o%b",
  tokenizers: [0, 1],
  topRules: {"program":[0,2]},
  specialized: [{term: 31, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
