// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,let:8, true:98, false:100, if:44, then:46, elif:50, else:54, end:56, loop:60, while:64, do:66, repeat:70, until:72, break:74, continue:76, yield:102, sleep:104}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")fOzQPOOOOQO'#Ca'#CaO!RQPO'#CoOOQO'#D['#D[OOQO'#DU'#DUO!WQPO'#DZQOQPOOO!kQPO'#C_O!pQPO'#CqO#UQPO'#CpO#aQPO'#CyO!pQPO'#C{O#hQPO'#DOOOQO'#DT'#DTO!pQPO'#DTO!pQPO,59ZOOQO-E7S-E7SO#oQPO,58yO!pQPO'#CeO!pQPO'#ChO%UQQO,59]OOQO'#D^'#D^OOQO'#Cd'#CdOOQO'#DV'#DVO%]QPO,59[O!pQPO'#CtO#aQPO'#CvOOQO,59[,59[O%cQPO,59[O%hQPO,59eO%mQQO,59gO%tQPO,59jO%yQQO,59oO&|QQO1G.uO!pQPO1G.eO(PQQO,59POOQO,59S,59SO!pQPO,59UO!pQPO,59UO!pQPO,59UO!pQPO,59UO!pQPO,59UO(WQPO1G.wOOQO-E7T-E7TOOQO1G.v1G.vO(eQPO1G.vO(jQQO,59`OOQO,59b,59bOOQO1G/P1G/PO#aQPO1G/RO!pQPO1G/UO(qQQO7+$POOQO1G.k1G.kOOQO1G.p1G.pO+[QQO1G.pO+cQQO1G.pO-QQQO1G.pO-XQQO1G.pOOQO7+$c7+$cOOQO7+$b7+$bO(WQPO1G.zO-`QPO7+$mO-eQQO7+$pOOQO7+$f7+$fOOQO<<HX<<HX",
  stateData: ".h~O|OSPOS~OSVOfWOnYOpZOs[OuROvRO!PPO!T]O!U^O~Oz}P~PYOU_O~Oz}Xl}Xt}Xi}Xk}X~PYO!PPO~OVeOYbO]cO!PPO!RfO!SfO~OiiOkjOlkO~Ol}P~PYOt}P~PYOUrOSRafRanRapRasRauRavRazRa!PRa!TRa!URalRatRaiRakRa~O]vO_uO`wOaxObyO~OgzO~P$sOiiOkjOl|O~Ol!QO~Oq!RO~P$sOt!SO~OSwafwanwapwaswauwavwazwa!Pwa!Twa!Uwalwatwaiwakwa~P$sOScifcincipcisciucivcizci!Pci!Tci!Ucilcitciicikci~P$sOZ!UO~P$sOi}Pk}Pl}P~PYOl!]O~Og!^O~P$sOSRqfRqnRqpRqsRquRqvRqzRq!PRq!TRq!URqlRqtRqiRqkRq~P$sO_uO`^ia^ib^ig^iq^iS^if^in^ip^is^iu^iv^iz^i!P^i!T^i!U^iZ^il^it^ii^ik^i~O]^i~P)tO]vO~P)tO]vO_uO`wOb^ig^iq^iS^if^in^ip^is^iu^iv^iz^i!P^i!T^i!U^iZ^il^it^ii^ik^i~Oa^i~P+jOaxO~P+jOl!bO~OSrqfrqnrqprqsrqurqvrqzrq!Prq!Trq!Urqlrqtrqirqkrq~P$sO",
  goto: "%`!RPPP!SP!^PP!k!kPP!kP!kPPPP!S!S!{PP#VP#ZPP!SP!SPP!SPPPP!S#a#mPPP#s$YP$daROTY[jz!R!^`QOTY[jz!R!^QaVmeWZ^_bciruvwxy!SaXOTY[jz!R!^TgXhQlXR}h^TOY[jz!R!^R`TQhXR{hQUOQmYQo[Q!PjQ![zQ!_!RR!a!^aSOTY[jz!R!^QdWQnZQp^Qq_QsbQtcQ!OiQ!TrQ!VuQ!WvQ!XwQ!YxQ!ZyR!`!S",
  nodeNames: "⚠ Comment program Declaration let VariableName Assign Number Bool Parens ParenLeft ParenRight UnaryOp AddOp BinaryOp MulOp CompareOp LogicAnd LogicOr Assignment IfExpr If if then ElseIf elif Else else end LoopExpr loop WhileExpr while do RepeatUntilExpr repeat until break continue Instruction",
  maxTerm: 52,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "%q~RkX^!vpq!vqr!{st#Wvw#oxy#zyz$Pz{$U{|$Z}!O$Z!P!Q$U!Q![$`!^!_$s!_!`${!`!a$s!c!}%T#R#S%T#T#o%T#p#q%f#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~!{O|~Q#OP!_!`#RQ#WO`Q~#]SP~OY#WZ;'S#W;'S;=`#i<%lO#W~#lP;=`<%l#W~#rPvw#u~#zOa~~$POY~~$UOZ~~$ZO_~~$`O]~~$eQV~!O!P$k!Q![$`~$pPV~!Q![$kQ$xP`Q!_!`#RR%QPUP!_!`#R~%YS!P~!Q![%T!c!}%T#R#S%T#T#o%T~%iP#p#q%l~%qOb~",
  tokenizers: [0, 1],
  topRules: {"program":[0,2]},
  specialized: [{term: 47, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
